### PR TITLE
Add public constructor to internal classes which are instantiated via IoC

### LINKED ISSUE #17: Add public constructor to internal classes which are instantiated via IoC
Some IoC containers (such as [Castle Windsor](http://www.castleproject.org/)) don't support instantiation of internal objects with an internal C'tor.

- Add public constructor where neccessary
- Adjust NInject for testing to enforce a public constructor

### PR DESCRIPTION
**Pull request by marco-bertschi**
Fixes #17

### CODE REVIEW

**Review by pascalberger — COMMENTED** [review]
Would it make sense to also add a test case using Castle.Windsor?

**Comment by marco-bertschi** [comment]
> Would it make sense to also add a test case using Castle.Windsor?

Definitely, yes - I've create #22 for this.

**Comment by pascalberger** [comment]
Please rebase on `release/1.0.0` branch and set target branch to `release/1.0.0` on this pull request.

**Comment by marco-bertschi** [comment]
> 
> 
> Please rebase on `release/1.0.0` branch and set target branch to `release/1.0.0` on this pull request.

Done

**Review by pascalberger — COMMENTED** [review]
Can we add a comment to the empty constructors why they are required? Otherwise someone will quite likely remove them in the future. Otherwise LGTM

**Comment by marco-bertschi** [comment]
> 
> 
> Can we add a comment to the empty constructors why they are required? Otherwise someone will quite likely remove them in the future. Otherwise LGTM

Done that.

**Review by pascalberger — APPROVED** [review]

**Pull request merged**
